//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLCDesign
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShakuntEnterprisesEntities : DbContext
    {
        public ShakuntEnterprisesEntities()
            : base("name=ShakuntEnterprisesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TestCertificateRecord> TestCertificateRecords { get; set; }
        public virtual DbSet<TestCertificateResultRecord> TestCertificateResultRecords { get; set; }
    }
}
