//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLCDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCertificateRecord
    {
        public int Id { get; set; }
        public string CertificateNo { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Quanity { get; set; }
        public string InvoiceNo { get; set; }
        public string TradeDesignation { get; set; }
        public string Size { get; set; }
        public string BatchDate { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> ManufecturingDate { get; set; }
        public string Specification { get; set; }
        public string WeldingProcess { get; set; }
        public string ShieldingGas { get; set; }
        public string PreHeatInerpassTemp { get; set; }
        public string Type { get; set; }
        public string APMS { get; set; }
        public string FlowRate { get; set; }
        public string CurrentPolarity { get; set; }
        public string Volts { get; set; }
        public string TravelSpeed { get; set; }
        public string BaseMetal { get; set; }
        public string Element_MIN_C { get; set; }
        public string Element_MIN_SI { get; set; }
        public string Element_MIN_MN { get; set; }
        public string Element_MIN_P { get; set; }
        public string Element_MIN_S { get; set; }
        public string Element_MIN_NI { get; set; }
        public string Element_MIN_CR { get; set; }
        public string Element_MIN_MO { get; set; }
        public string Element_MIN_CU { get; set; }
        public string Element_MAX_C { get; set; }
        public string Element_MAX_SI { get; set; }
        public string Element_MAX_MN { get; set; }
        public string Element_MAX_P { get; set; }
        public string Element_MAX_S { get; set; }
        public string Element_MAX_NI { get; set; }
        public string Element_MAX_CR { get; set; }
        public string Element_MAX_MO { get; set; }
        public string Element_MAX_CU { get; set; }
        public string Test_MIN_UTS { get; set; }
        public string Test_MIN_YS { get; set; }
        public string Test_MIN_Elongation { get; set; }
        public string Test_MAX_UTS { get; set; }
        public string Test_MAX_YS { get; set; }
        public string Test_MAX_Elongation { get; set; }
        public string Test_Temp { get; set; }
        public string Test_ImpectValue { get; set; }
        public string Test_Condition { get; set; }
        public string Size_StandardValue { get; set; }
        public string Size_ActualValue { get; set; }
        public string Coating_StandardValue { get; set; }
        public string Coating_ActualValue { get; set; }
        public string UTSWire_StandardValue { get; set; }
        public string UTSWire_ActualValue { get; set; }
        public string CastDia_StandardValue { get; set; }
        public string CastDia_ActualValue { get; set; }
        public string Helix_StandardValue { get; set; }
        public string Helix_ActualValue { get; set; }
        public string OtherTest_Radio_Specs { get; set; }
        public string OtherTest_FaceBend_Specs { get; set; }
        public string OtherTest_Filled_Specs { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> IsApproved { get; set; }
        public string HideSection { get; set; }
        public string Certificate_Type { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public string CombineBatchNo { get; set; }
    }
}
