//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDLCDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeDesignationMaster
    {
        public int Id { get; set; }
        public string Size { get; set; }
        public string TradeDesignation { get; set; }
        public string Specification { get; set; }
        public string WeldingProcess { get; set; }
        public string ShieldingGas { get; set; }
        public string PreHeatInerpassTemp { get; set; }
        public string Type { get; set; }
        public string FlowRate { get; set; }
        public string CurrentPolarity { get; set; }
        public string BaseMetal { get; set; }
        public string Element_MIN_C { get; set; }
        public string Element_MIN_SI { get; set; }
        public string Element_MIN_MN { get; set; }
        public string Element_MIN_P { get; set; }
        public string Element_MIN_S { get; set; }
        public string Element_MIN_NI { get; set; }
        public string Element_MIN_CR { get; set; }
        public string Element_MIN_MO { get; set; }
        public string Element_MIN_CU { get; set; }
        public string Element_MAX_C { get; set; }
        public string Element_MAX_SI { get; set; }
        public string Element_MAX_MN { get; set; }
        public string Element_MAX_P { get; set; }
        public string Element_MAX_S { get; set; }
        public string Element_MAX_NI { get; set; }
        public string Element_MAX_CR { get; set; }
        public string Element_MAX_MO { get; set; }
        public string Element_MAX_CU { get; set; }
        public string Test_MIN_UTS { get; set; }
        public string Test_MIN_YS { get; set; }
        public string Test_MIN_Elongation { get; set; }
        public string Test_MAX_UTS { get; set; }
        public string Test_MAX_YS { get; set; }
        public string Test_MAX_Elongation { get; set; }
        public string Test_Temp { get; set; }
        public string Test_ImpectDegree { get; set; }
        public string Test_ImpectValue { get; set; }
        public string Test_Condition { get; set; }
        public string CompositionHeading { get; set; }
        public string OtherTest_Radio_Specs { get; set; }
        public string OtherTest_FaceBend_Specs { get; set; }
        public string OtherTest_Filled_Specs { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    }
}
